### ISSUE TITLE
A big f()cking error

### ISSUE THREAD

**Issue by Slavfucious** [Smug246/Luna-Token-Grabber#43]
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 72, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 358, in connect
  File "urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000017A98852BF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='discord.com', port=443): Max retries exceeded with url: /api/v10/webhooks/1030597433815736410/uRfgnV4ymQVtLPpFSg5UoYMSqmxWWCEbwzOkAAf84V_INkpwJZWJYQ8s_BfIyr9r1Ka-?wait=0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017A98852BF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phasmophobia.py", line 720, in <module>
  File "phasmophobia.py", line 76, in Luna
  File "phasmophobia.py", line 65, in main
  File "discord\webhook\sync.py", line 1028, in send
  File "discord\webhook\sync.py", line 297, in execute_webhook
  File "discord\webhook\sync.py", line 166, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 565, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='discord.com', port=443): Max retries exceeded with url: /api/v10/webhooks/1030597433815736410/uRfgnV4ymQVtLPpFSg5UoYMSqmxWWCEbwzOkAAf84V_INkpwJZWJYQ8s_BfIyr9r1Ka-?wait=0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017A98852BF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by Smug246** [comment]
tf is that

**Comment by KingKrex69** [comment]
> 

Create a new webhook because its {"message": "Invalid Webhook Token", "code": 50027}

**Comment by Smug246** [comment]
closing because of no response
