### ISSUE TITLE
eror not find

### ISSUE THREAD

**Issue by hiro1434** [Smug246/Luna-Token-Grabber#64]
Traceback (most recent call last):
  File "obfuscated_compressed_dsadas.py", line 21, in <module>
  File "<string>", line 1, in <module>
  File "nmnpjbhpzykhbbk", line 888, in <module>
  File "nmnpjbhpzykhbbk", line 72, in Luna
  File "nmnpjbhpzykhbbk", line 51, in main
  File "discord\file.py", line 97, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dadasd\\AppData\\Local\\Luna-Logged-king.zip'

**Comment by Smug246** [comment]
try going to C:\Users\dadasd\AppData\Local and see if that file is there

**Comment by hiro1434** [comment]
fixed thanks ❤️
